declare enum BCOutlineViewNodeExpansionState {
  BCOutlineViewNodeExpansionStateModelExpanded,
  BCOutlineViewNodeExpansionStateUserExpanded,
  BCOutlineViewNodeExpansionStateDragAutoExpanded,
  BCOutlineViewNodeExpansionStateModelCollapsed,
  BCOutlineViewNodeExpansionStateUserCollapsed,
  BCOutlineViewNodeExpansionStateDragAutoCollapsed,
}

