declare enum BCTableRowViewExpansionTransitionState {
  BCTableRowViewExpansionTransitionStateAtRest,
  BCTableRowViewExpansionTransitionStateCollapsing,
  BCTableRowViewExpansionTransitionStateExpanding,
}

