interface CAEmitterCellUninitialized<InitializedType = CAEmitterCell> extends NSObjectUninitialized<CAEmitterCell> {}

interface CAEmitterCell extends NSObject, INSSecureCoding, ICAMediaTiming {
  shouldArchiveValueForKey(key: NSString | string): boolean;

  name(): NSString;
  setName(name: NSString | string): void;
  enabled(): boolean;
  setEnabled(enabled: boolean): void;
  birthRate(): number;
  setBirthRate(birthRate: number): void;
  lifetime(): number;
  setLifetime(lifetime: number): void;
  lifetimeRange(): number;
  setLifetimeRange(lifetimeRange: number): void;
  emissionLatitude(): CGFloat;
  setEmissionLatitude(emissionLatitude: CGFloat): void;
  emissionLongitude(): CGFloat;
  setEmissionLongitude(emissionLongitude: CGFloat): void;
  emissionRange(): CGFloat;
  setEmissionRange(emissionRange: CGFloat): void;
  velocity(): CGFloat;
  setVelocity(velocity: CGFloat): void;
  velocityRange(): CGFloat;
  setVelocityRange(velocityRange: CGFloat): void;
  xAcceleration(): CGFloat;
  setXAcceleration(xAcceleration: CGFloat): void;
  yAcceleration(): CGFloat;
  setYAcceleration(yAcceleration: CGFloat): void;
  zAcceleration(): CGFloat;
  setZAcceleration(zAcceleration: CGFloat): void;
  scale(): CGFloat;
  setScale(scale: CGFloat): void;
  scaleRange(): CGFloat;
  setScaleRange(scaleRange: CGFloat): void;
  scaleSpeed(): CGFloat;
  setScaleSpeed(scaleSpeed: CGFloat): void;
  spin(): CGFloat;
  setSpin(spin: CGFloat): void;
  spinRange(): CGFloat;
  setSpinRange(spinRange: CGFloat): void;
  color(): CGColorRef;
  setColor(color: CGColorRef): void;
  redRange(): number;
  setRedRange(redRange: number): void;
  greenRange(): number;
  setGreenRange(greenRange: number): void;
  blueRange(): number;
  setBlueRange(blueRange: number): void;
  alphaRange(): number;
  setAlphaRange(alphaRange: number): void;
  redSpeed(): number;
  setRedSpeed(redSpeed: number): void;
  greenSpeed(): number;
  setGreenSpeed(greenSpeed: number): void;
  blueSpeed(): number;
  setBlueSpeed(blueSpeed: number): void;
  alphaSpeed(): number;
  setAlphaSpeed(alphaSpeed: number): void;
  contents(): any;
  setContents(contents: any): void;
  contentsRect(): CGRect;
  setContentsRect(contentsRect: CGRect): void;
  contentsScale(): CGFloat;
  setContentsScale(contentsScale: CGFloat): void;
  minificationFilter(): NSString;
  setMinificationFilter(minificationFilter: NSString | string): void;
  magnificationFilter(): NSString;
  setMagnificationFilter(magnificationFilter: NSString | string): void;
  minificationFilterBias(): number;
  setMinificationFilterBias(minificationFilterBias: number): void;
  emitterCells(): NSArray<any>;
  setEmitterCells(emitterCells: NSArray<any> | any[]): void;
  style(): NSDictionary<any, any>;
  setStyle(style: NSDictionary<any, any> | {[key: string]: any}): void;
  beginTime(): CFTimeInterval;
  setBeginTime(beginTime: CFTimeInterval): void;
  duration(): CFTimeInterval;
  setDuration(duration: CFTimeInterval): void;
  speed(): number;
  setSpeed(speed: number): void;
  timeOffset(): CFTimeInterval;
  setTimeOffset(timeOffset: CFTimeInterval): void;
  repeatCount(): number;
  setRepeatCount(repeatCount: number): void;
  repeatDuration(): CFTimeInterval;
  setRepeatDuration(repeatDuration: CFTimeInterval): void;
  autoreverses(): boolean;
  setAutoreverses(autoreverses: boolean): void;
  fillMode(): CAMediaTimingFillMode;
  setFillMode(fillMode: CAMediaTimingFillMode): void;
}

declare const CAEmitterCell: {
  alloc(): CAEmitterCellUninitialized;
  class(): CAEmitterCell;
  emitterCell(): CAEmitterCell;
  defaultValueForKey(key: NSString | string): any;
  load(): void;
  instancesRespondToSelector(aSelector: string): boolean;
  conformsToProtocol(protocol: Protocol): boolean;
  instanceMethodForSelector(aSelector: string): IMP;
  isSubclassOfClass(aClass: any): boolean;
  hash(): NSUInteger;
  superclass(): any;
  description(): NSString;
  debugDescription(): NSString;
  useStoredAccessor(): boolean;
  keyPathsForValuesAffectingValueForKey(key: NSString | string): NSSet<any>;
  automaticallyNotifiesObserversForKey(key: NSString | string): boolean;
  setKeys_triggerChangeNotificationsForDependentKey(keys: NSArray<any> | any[], dependentKey: NSString | string): void;
  classFallbacksForKeyedArchiver(): NSArray<any>;
  classForKeyedUnarchiver(): any;
  version(): NSInteger;
  setVersion(aVersion: NSInteger): void;
  cancelPreviousPerformRequestsWithTarget_selector_object(aTarget: any, aSelector: string, anArgument: any | null): void;
  cancelPreviousPerformRequestsWithTarget(aTarget: any): void;
  exposeBinding(binding: NSBindingName): void;
  setDefaultPlaceholder_forMarker_withBinding(placeholder: any | null, marker: any | null, binding: NSBindingName): void;
  defaultPlaceholderForMarker_withBinding(marker: any | null, binding: NSBindingName): any;
  mo_swizzleAdditions(): void;
  mo_mocha(): MOClassDescription;
  isSelectorExcludedFromMochaScript(selector: string): boolean;
  selectorForMochaPropertyName(propertyName: NSString | string): string;
  supportsSecureCoding(): boolean;
  accessInstanceVariablesDirectly(): boolean;

}

