declare enum CGWindowLevelKey {
  kCGBaseWindowLevelKey = 0,
  kCGMinimumWindowLevelKey,
  kCGDesktopWindowLevelKey,
  kCGBackstopMenuLevelKey,
  kCGNormalWindowLevelKey,
  kCGFloatingWindowLevelKey,
  kCGTornOffMenuWindowLevelKey,
  kCGDockWindowLevelKey,
  kCGMainMenuWindowLevelKey,
  kCGStatusWindowLevelKey,
  kCGModalPanelWindowLevelKey,
  kCGPopUpMenuWindowLevelKey,
  kCGDraggingWindowLevelKey,
  kCGScreenSaverWindowLevelKey,
  kCGMaximumWindowLevelKey,
  kCGOverlayWindowLevelKey,
  kCGHelpWindowLevelKey,
  kCGUtilityWindowLevelKey,
  kCGDesktopIconWindowLevelKey,
  kCGCursorWindowLevelKey,
  kCGAssistiveTechHighWindowLevelKey,
  kCGNumberOfWindowLevelKeys,
}

