interface MSColorInspectorCircularGradientTabActionUninitialized<InitializedType = MSColorInspectorCircularGradientTabAction> extends MSColorInspectorModePickerActionUninitialized<MSColorInspectorCircularGradientTabAction> {}
interface MSColorInspectorCircularGradientTabAction extends MSColorInspectorModePickerAction {
}
declare const MSColorInspectorCircularGradientTabAction: {
  alloc(): MSColorInspectorCircularGradientTabActionUninitialized;
  class(): MSColorInspectorCircularGradientTabAction;
}

