declare enum MSLayoutAttribute {
  MSLayoutAttributeLeft,
  MSLayoutAttributeRight,
  MSLayoutAttributeTop,
  MSLayoutAttributeBottom,
  MSLayoutAttributeWidth,
  MSLayoutAttributeHeight,
  MSLayoutAttributeCenterX,
  MSLayoutAttributeCenterY,
  MSLayoutAttributeBaseline,
  MSLayoutAttributeMidXHeight,
  MSLayoutAttributeCapHeight,
  MSLayoutAttributeGuideX,
  MSLayoutAttributeGuideY,
  MSLayoutAttributePointMinimum = 20,
  MSLayoutAttributeTopLeft,
  MSLayoutAttributeTopRight,
  MSLayoutAttributeBottomLeft,
  MSLayoutAttributeBottomRight,
  MSLayoutAttributeMidTop,
  MSLayoutAttributeMidLeft,
  MSLayoutAttributeMidRight,
  MSLayoutAttributeMidBottom,
  MSLayoutAttributePointMaximum,
  MSLayoutAttributeNotAnAttribute,
}

