interface MSMultipleInnerShadowInspectorViewControllerUninitialized<InitializedType = MSMultipleInnerShadowInspectorViewController> extends MSMultipleShadowInspectorViewControllerUninitialized<MSMultipleInnerShadowInspectorViewController> {}
interface MSMultipleInnerShadowInspectorViewController extends MSMultipleShadowInspectorViewController {
}
declare const MSMultipleInnerShadowInspectorViewController: {
  alloc(): MSMultipleInnerShadowInspectorViewControllerUninitialized;
  class(): MSMultipleInnerShadowInspectorViewController;
}

