interface MSOverrideManagementTitleViewControllerUninitialized<InitializedType = MSOverrideManagementTitleViewController> extends MSOverrideManagementViewControllerUninitialized<MSOverrideManagementTitleViewController> {}
interface MSOverrideManagementTitleViewController extends MSOverrideManagementViewController {
}
declare const MSOverrideManagementTitleViewController: {
  alloc(): MSOverrideManagementTitleViewControllerUninitialized;
  class(): MSOverrideManagementTitleViewController;
}

