interface MSSliceExportGroupContentsOnlyInspectorItemUninitialized<InitializedType = MSSliceExportGroupContentsOnlyInspectorItem> extends MSInspectorItemUninitialized<MSSliceExportGroupContentsOnlyInspectorItem> {}
interface MSSliceExportGroupContentsOnlyInspectorItem extends MSInspectorItem {
}
declare const MSSliceExportGroupContentsOnlyInspectorItem: {
  alloc(): MSSliceExportGroupContentsOnlyInspectorItemUninitialized;
  class(): MSSliceExportGroupContentsOnlyInspectorItem;
}

