declare enum NSAccessibilityCustomRotorType {
  NSAccessibilityCustomRotorTypeCustom = 0,
  NSAccessibilityCustomRotorTypeAny = 1,
  NSAccessibilityCustomRotorTypeAnnotation,
  NSAccessibilityCustomRotorTypeBoldText,
  NSAccessibilityCustomRotorTypeHeading,
  NSAccessibilityCustomRotorTypeHeadingLevel1,
  NSAccessibilityCustomRotorTypeHeadingLevel2,
  NSAccessibilityCustomRotorTypeHeadingLevel3,
  NSAccessibilityCustomRotorTypeHeadingLevel4,
  NSAccessibilityCustomRotorTypeHeadingLevel5,
  NSAccessibilityCustomRotorTypeHeadingLevel6,
  NSAccessibilityCustomRotorTypeImage,
  NSAccessibilityCustomRotorTypeItalicText,
  NSAccessibilityCustomRotorTypeLandmark,
  NSAccessibilityCustomRotorTypeLink,
  NSAccessibilityCustomRotorTypeList,
  NSAccessibilityCustomRotorTypeMisspelledWord,
  NSAccessibilityCustomRotorTypeTable,
  NSAccessibilityCustomRotorTypeTextField,
  NSAccessibilityCustomRotorTypeUnderlinedText,
  NSAccessibilityCustomRotorTypeVisitedLink,
}

