declare enum NSAlignmentOptions {
  NSAlignMinXInward = 1 << 0,
  NSAlignMinYInward = 1 << 1,
  NSAlignMaxXInward = 1 << 2,
  NSAlignMaxYInward = 1 << 3,
  NSAlignWidthInward = 1 << 4,
  NSAlignHeightInward = 1 << 5,
  NSAlignMinXOutward = 1 << 8,
  NSAlignMinYOutward = 1 << 9,
  NSAlignMaxXOutward = 1 << 10,
  NSAlignMaxYOutward = 1 << 11,
  NSAlignWidthOutward = 1 << 12,
  NSAlignHeightOutward = 1 << 13,
  NSAlignMinXNearest = 1 << 16,
  NSAlignMinYNearest = 1 << 17,
  NSAlignMaxXNearest = 1 << 18,
  NSAlignMaxYNearest = 1 << 19,
  NSAlignWidthNearest = 1 << 20,
  NSAlignHeightNearest = 1 << 21,
  NSAlignRectFlipped = 1 << 63,
  NSAlignAllEdgesInward,
  NSAlignAllEdgesOutward,
  NSAlignAllEdgesNearest,
}

