interface NSArrayUninitialized<ObjectType, InitializedType = NSArray<ObjectType>> extends NSObjectUninitialized<NSArray<ObjectType>> {
  initWithObjects_count(objects: ObjectType[], cnt: NSUInteger): InitializedType;
  initWithCoder(aDecoder: NSCoder): InitializedType;
  initWithObjects(firstObj: ObjectType, ...args: any[]): InitializedType;
  initWithArray(array: NSArray<any> | any[]): InitializedType;
  initWithArray_copyItems(array: NSArray<any> | any[], flag: boolean): InitializedType;
  initWithContentsOfURL_error(url: NSURL, error: MOPointer<NSError>): InitializedType;
  initWithContentsOfFile(path: NSString | string): InitializedType;
  initWithContentsOfURL(url: NSURL): InitializedType;
}

interface NSArray<ObjectType> extends NSObject, INSCopying, INSMutableCopying, INSSecureCoding, INSFastEnumeration {

  [key: number]: ObjectType | Function;
  [key: string]: ObjectType | Function;
  objectAtIndex(index: NSUInteger): ObjectType;
  arrayByAddingObject(anObject: ObjectType): NSArray<any>;
  arrayByAddingObjectsFromArray(otherArray: NSArray<any> | any[]): NSArray<any>;
  componentsJoinedByString(separator: NSString | string): NSString;
  containsObject(anObject: ObjectType): boolean;
  descriptionWithLocale(locale: any | null): NSString;
  descriptionWithLocale_indent(locale: any | null, level: NSUInteger): NSString;
  firstObjectCommonWithArray(otherArray: NSArray<any> | any[]): ObjectType;
  indexOfObject(anObject: ObjectType): NSUInteger;
  indexOfObject_inRange(anObject: ObjectType, range: NSRange): NSUInteger;
  indexOfObjectIdenticalTo(anObject: ObjectType): NSUInteger;
  indexOfObjectIdenticalTo_inRange(anObject: ObjectType, range: NSRange): NSUInteger;
  isEqualToArray(otherArray: NSArray<any> | any[]): boolean;
  objectEnumerator(): NSEnumerator<any>;
  reverseObjectEnumerator(): NSEnumerator<any>;
  sortedArrayUsingSelector(comparator: string): NSArray<any>;
  subarrayWithRange(range: NSRange): NSArray<any>;
  writeToURL_error(url: NSURL, error: MOPointer<NSError>): boolean;
  makeObjectsPerformSelector(aSelector: string): void;
  makeObjectsPerformSelector_withObject(aSelector: string, argument: any | null): void;
  objectsAtIndexes(indexes: NSIndexSet): NSArray<any>;
  objectAtIndexedSubscript(idx: NSUInteger): ObjectType;
  enumerateObjectsUsingBlock(block: Block): void;
  enumerateObjectsWithOptions_usingBlock(opts: NSEnumerationOptions, block: Block): void;
  enumerateObjectsAtIndexes_options_usingBlock(s: NSIndexSet, opts: NSEnumerationOptions, block: Block): void;
  indexOfObjectPassingTest(predicate: Block): NSUInteger;
  indexOfObjectWithOptions_passingTest(opts: NSEnumerationOptions, predicate: Block): NSUInteger;
  indexOfObjectAtIndexes_options_passingTest(s: NSIndexSet, opts: NSEnumerationOptions, predicate: Block): NSUInteger;
  indexesOfObjectsPassingTest(predicate: Block): NSIndexSet;
  indexesOfObjectsWithOptions_passingTest(opts: NSEnumerationOptions, predicate: Block): NSIndexSet;
  indexesOfObjectsAtIndexes_options_passingTest(s: NSIndexSet, opts: NSEnumerationOptions, predicate: Block): NSIndexSet;
  sortedArrayUsingComparator(cmptr: NSComparator): NSArray<any>;
  sortedArrayWithOptions_usingComparator(opts: NSSortOptions, cmptr: NSComparator): NSArray<any>;
  indexOfObject_inSortedRange_options_usingComparator(obj: ObjectType, r: NSRange, opts: NSBinarySearchingOptions, cmp: NSComparator): NSUInteger;
  getObjects(objects: ObjectType[]): void;
  writeToFile_atomically(path: NSString | string, useAuxiliaryFile: boolean): boolean;
  writeToURL_atomically(url: NSURL, atomically: boolean): boolean;
  valueForKey(key: NSString | string): any;
  setValue_forKey(value: any | null, key: NSString | string): void;
  addObserver_toObjectsAtIndexes_forKeyPath_options_context(observer: NSObject, indexes: NSIndexSet, keyPath: NSString | string, options: NSKeyValueObservingOptions, context: void | null): void;
  removeObserver_fromObjectsAtIndexes_forKeyPath_context(observer: NSObject, indexes: NSIndexSet, keyPath: NSString | string, context: void | null): void;
  removeObserver_fromObjectsAtIndexes_forKeyPath(observer: NSObject, indexes: NSIndexSet, keyPath: NSString | string): void;
  addObserver_forKeyPath_options_context(observer: NSObject, keyPath: NSString | string, options: NSKeyValueObservingOptions, context: void | null): void;
  removeObserver_forKeyPath_context(observer: NSObject, keyPath: NSString | string, context: void | null): void;
  removeObserver_forKeyPath(observer: NSObject, keyPath: NSString | string): void;
  pathsMatchingExtensions(filterTypes: NSArray<any> | any[]): NSArray<any>;
  filteredArrayUsingPredicate(predicate: NSPredicate): NSArray<any>;
  sortedArrayUsingDescriptors(sortDescriptors: NSArray<any> | any[]): NSArray<any>;
  front(): NSArray<any>;
  tail(): NSArray<any>;
  arrayByRemovingLastObject(): NSArray<any>;
  enumerateTailUsingBlock(block: Block): void;
  reversedArray(): NSArray<any>;
  map(block: Block): NSArray<any>;
  compactMap(block: Block | null): NSArray<any>;
  mapWithIndex(block: Block): NSArray<any>;
  enumerate(block: Block): void;
  enumerateWithIndex(block: Block): void;
  filter(block: Block): NSArray<any>;
  containsObjectPassingTest(predicate: Block): boolean;
  firstObjectPassingTest(predicate: Block): ObjectType;
  indexOfFirstObjectPassingTest(predicate: Block): NSUInteger;
  filterWithIndex(block: Block): NSArray<any>;
  filteredByObjectsOfClass(aClass: any): NSArray<any>;
  containsObjectOfClass(aClass: any): boolean;
  containsOnlyObjectsOfClass(aClass: any): boolean;
  firstObjectOfClass(aClass: any): any;
  sum(block: BCSumBlock): CGFloat;
  arrayByRemovingNull(): NSArray<any>;
  copyDeep(): any;
  sortedArray(): NSArray<any>;
  sortedArrayUsingKey(key: NSString | string): NSArray<any>;
  sortedArrayUsingKey_selector(key: NSString | string, action: string): NSArray<any>;
  shuffledArray(): NSArray<any>;
  arrayByRemovingObject(anObject: any): NSArray<any>;
  arrayByRemovingObjects(objects: NSArray<any> | any[]): NSArray<any>;
  arrayByAddingObjects(firstObj: any, ...args: any[]): NSArray<any>;
  dictionaryByIndexingObjectForKey(aKey: NSString | string): NSDictionary<any, any>;
  isValidIndex(anIndex: NSUInteger): boolean;
  objectAtIndexOrNil(index: NSUInteger): ObjectType;
  subArrayToIndex(anIndex: NSUInteger): NSArray<any>;
  uniqueObjects(): NSArray<any>;
  rotateTwoDimensionalArray(): NSArray<any>;
  indexOfSubArray(array: NSArray<any> | any[]): NSUInteger;
  mapWithMaxConcurrencyCount_usingBlock_completionBlock(maxConcurrentCount: NSInteger, block: Block, completionBlock: BCConcurrentMapCompletionBlock): void;
  applyBlockConcurrentlyAndCountSuccess(block: Block): NSUInteger;
  mo_objectForIndexedSubscript(idx: NSUInteger): any;
  cloudObjectsOfType_parentObject(type: any, parent: SCKObject | null): NSArray<any>;
  length(): NSUInteger;
  copyWithZone(zone: NSZone | null): any;
  mutableCopyWithZone(zone: NSZone | null): any;
  countByEnumeratingWithState_objects_count(state: NSFastEnumerationState, buffer: any[], len: NSUInteger): NSUInteger;

  count(): NSUInteger;
  description(): NSString;
  firstObject(): ObjectType;
  lastObject(): ObjectType;
  sortedArrayHint(): NSData;
}

declare const NSArray: {
  alloc<ObjectType>(): NSArrayUninitialized<ObjectType>;
  class(): NSArray;
  array<ObjectType>(): NSArray<ObjectType>;
  arrayWithObject<ObjectType>(anObject: ObjectType): NSArray<ObjectType>;
  arrayWithObjects_count<ObjectType>(objects: ObjectType[], cnt: NSUInteger): NSArray<ObjectType>;
  arrayWithObjects<ObjectType>(firstObj: ObjectType, ...args: any[]): NSArray<ObjectType>;
  arrayWithArray<ObjectType>(array: NSArray<any> | any[]): NSArray<ObjectType>;
  arrayWithContentsOfURL_error(url: NSURL, error: MOPointer<NSError>): NSArray<any>;
  arrayWithContentsOfFile(path: NSString | string): NSArray<any>;
  arrayWithContentsOfURL(url: NSURL): NSArray<any>;
  flattenedArrays(arrays: NSArray<any> | any[]): NSArray<any>;
  arrayWithCapacity_fill(count: NSUInteger, block: Block): any;
  arrayByMergingArrays(array: NSArray<any> | any[]): NSArray<any>;
  load(): void;
  instancesRespondToSelector(aSelector: string): boolean;
  conformsToProtocol(protocol: Protocol): boolean;
  instanceMethodForSelector(aSelector: string): IMP;
  isSubclassOfClass(aClass: any): boolean;
  hash(): NSUInteger;
  superclass(): any;
  description(): NSString;
  debugDescription(): NSString;
  useStoredAccessor(): boolean;
  keyPathsForValuesAffectingValueForKey(key: NSString | string): NSSet<any>;
  automaticallyNotifiesObserversForKey(key: NSString | string): boolean;
  setKeys_triggerChangeNotificationsForDependentKey(keys: NSArray<any> | any[], dependentKey: NSString | string): void;
  classFallbacksForKeyedArchiver(): NSArray<any>;
  classForKeyedUnarchiver(): any;
  version(): NSInteger;
  setVersion(aVersion: NSInteger): void;
  cancelPreviousPerformRequestsWithTarget_selector_object(aTarget: any, aSelector: string, anArgument: any | null): void;
  cancelPreviousPerformRequestsWithTarget(aTarget: any): void;
  exposeBinding(binding: NSBindingName): void;
  setDefaultPlaceholder_forMarker_withBinding(placeholder: any | null, marker: any | null, binding: NSBindingName): void;
  defaultPlaceholderForMarker_withBinding(marker: any | null, binding: NSBindingName): any;
  mo_swizzleAdditions(): void;
  mo_mocha(): MOClassDescription;
  isSelectorExcludedFromMochaScript(selector: string): boolean;
  selectorForMochaPropertyName(propertyName: NSString | string): string;
  supportsSecureCoding(): boolean;
  accessInstanceVariablesDirectly(): boolean;

}

