declare enum NSDateComponentsFormatterZeroFormattingBehavior {
  NSDateComponentsFormatterZeroFormattingBehaviorNone,
  NSDateComponentsFormatterZeroFormattingBehaviorDefault,
  NSDateComponentsFormatterZeroFormattingBehaviorDropLeading,
  NSDateComponentsFormatterZeroFormattingBehaviorDropMiddle,
  NSDateComponentsFormatterZeroFormattingBehaviorDropTrailing,
  NSDateComponentsFormatterZeroFormattingBehaviorDropAll,
  NSDateComponentsFormatterZeroFormattingBehaviorPad,
}

