declare enum NSEventMask {
  NSEventMaskLeftMouseDown = 1 << NSEventType.NSEventTypeLeftMouseDown,
  NSEventMaskLeftMouseUp = 1 << NSEventType.NSEventTypeLeftMouseUp,
  NSEventMaskRightMouseDown = 1 << NSEventType.NSEventTypeRightMouseDown,
  NSEventMaskRightMouseUp = 1 << NSEventType.NSEventTypeRightMouseUp,
  NSEventMaskMouseMoved = 1 << NSEventType.NSEventTypeMouseMoved,
  NSEventMaskLeftMouseDragged = 1 << NSEventType.NSEventTypeLeftMouseDragged,
  NSEventMaskRightMouseDragged = 1 << NSEventType.NSEventTypeRightMouseDragged,
  NSEventMaskMouseEntered = 1 << NSEventType.NSEventTypeMouseEntered,
  NSEventMaskMouseExited = 1 << NSEventType.NSEventTypeMouseExited,
  NSEventMaskKeyDown = 1 << NSEventType.NSEventTypeKeyDown,
  NSEventMaskKeyUp = 1 << NSEventType.NSEventTypeKeyUp,
  NSEventMaskFlagsChanged = 1 << NSEventType.NSEventTypeFlagsChanged,
  NSEventMaskAppKitDefined = 1 << NSEventType.NSEventTypeAppKitDefined,
  NSEventMaskSystemDefined = 1 << NSEventType.NSEventTypeSystemDefined,
  NSEventMaskApplicationDefined = 1 << NSEventType.NSEventTypeApplicationDefined,
  NSEventMaskPeriodic = 1 << NSEventType.NSEventTypePeriodic,
  NSEventMaskCursorUpdate = 1 << NSEventType.NSEventTypeCursorUpdate,
  NSEventMaskScrollWheel = 1 << NSEventType.NSEventTypeScrollWheel,
  NSEventMaskTabletPoint = 1 << NSEventType.NSEventTypeTabletPoint,
  NSEventMaskTabletProximity = 1 << NSEventType.NSEventTypeTabletProximity,
  NSEventMaskOtherMouseDown = 1 << NSEventType.NSEventTypeOtherMouseDown,
  NSEventMaskOtherMouseUp = 1 << NSEventType.NSEventTypeOtherMouseUp,
  NSEventMaskOtherMouseDragged = 1 << NSEventType.NSEventTypeOtherMouseDragged,
  NSEventMaskGesture = 1 << NSEventType.NSEventTypeGesture,
  NSEventMaskMagnify = 1 << NSEventType.NSEventTypeMagnify,
  NSEventMaskSwipe = 1 << NSEventType.NSEventTypeSwipe,
  NSEventMaskRotate = 1 << NSEventType.NSEventTypeRotate,
  NSEventMaskBeginGesture = 1 << NSEventType.NSEventTypeBeginGesture,
  NSEventMaskEndGesture = 1 << NSEventType.NSEventTypeEndGesture,
  NSEventMaskSmartMagnify = 1 << NSEventType.NSEventTypeSmartMagnify,
  NSEventMaskPressure = 1 << NSEventType.NSEventTypePressure,
  NSEventMaskDirectTouch = 1 << NSEventType.NSEventTypeDirectTouch,
  NSEventMaskAny,
}

