declare enum NSFontDescriptorSymbolicTraits {
  NSFontDescriptorTraitItalic = 1 << 0,
  NSFontDescriptorTraitBold = 1 << 1,
  NSFontDescriptorTraitExpanded = 1 << 5,
  NSFontDescriptorTraitCondensed = 1 << 6,
  NSFontDescriptorTraitMonoSpace = 1 << 10,
  NSFontDescriptorTraitVertical = 1 << 11,
  NSFontDescriptorTraitUIOptimized = 1 << 12,
  NSFontDescriptorTraitTightLeading = 1 << 15,
  NSFontDescriptorTraitLooseLeading = 1 << 16,
  NSFontDescriptorClassMask = 0xF0000000,
  NSFontDescriptorClassUnknown = 0 << 28,
  NSFontDescriptorClassOldStyleSerifs = 1 << 28,
  NSFontDescriptorClassTransitionalSerifs = 2 << 28,
  NSFontDescriptorClassModernSerifs = 3 << 28,
  NSFontDescriptorClassClarendonSerifs = 4 << 28,
  NSFontDescriptorClassSlabSerifs = 5 << 28,
  NSFontDescriptorClassFreeformSerifs = 7 << 28,
  NSFontDescriptorClassSansSerif = 8 << 28,
  NSFontDescriptorClassOrnamentals = 9 << 28,
  NSFontDescriptorClassScripts = 10 << 28,
  NSFontDescriptorClassSymbolic = 12 << 28,
}

