declare enum NSMeasurementFormatterUnitOptions {
  NSMeasurementFormatterUnitOptionsProvidedUnit,
  NSMeasurementFormatterUnitOptionsNaturalScale,
  NSMeasurementFormatterUnitOptionsTemperatureWithoutUnit,
}

