declare enum NSOpenGLContextParameter {
  NSOpenGLContextParameterSwapInterval           NS_OPENGL_ENUM_DEPRECATED(10_0,
  10_14) = 222,
  NSOpenGLContextParameterSurfaceOrder           NS_OPENGL_ENUM_DEPRECATED(10_0,
  10_14) = 235,
  NSOpenGLContextParameterSurfaceOpacity         NS_OPENGL_ENUM_DEPRECATED(10_0,
  10_14) = 236,
  NSOpenGLContextParameterSurfaceBackingSize     NS_OPENGL_ENUM_DEPRECATED(10_0,
  10_14) = 304,
  NSOpenGLContextParameterReclaimResources       NS_OPENGL_ENUM_DEPRECATED(10_0,
  10_14) = 308,
  NSOpenGLContextParameterCurrentRendererID      NS_OPENGL_ENUM_DEPRECATED(10_0,
  10_14) = 309,
  NSOpenGLContextParameterGPUVertexProcessing    NS_OPENGL_ENUM_DEPRECATED(10_0,
  10_14) = 310,
  NSOpenGLContextParameterGPUFragmentProcessing  NS_OPENGL_ENUM_DEPRECATED(10_0,
  10_14) = 311,
  NSOpenGLContextParameterHasDrawable            NS_OPENGL_ENUM_DEPRECATED(10_0,
  10_14) = 314,
  NSOpenGLContextParameterMPSwapsInFlight        NS_OPENGL_ENUM_DEPRECATED(10_0,
  10_14) = 315,
  NSOpenGLContextParameterSwapRectangle = 200,
  NSOpenGLContextParameterSwapRectangleEnable = 201,
  NSOpenGLContextParameterRasterizationEnable = 221,
  NSOpenGLContextParameterStateValidation = 301,
  NSOpenGLContextParameterSurfaceSurfaceVolatile = 306,
}

