declare enum NSSplitViewItemCollapseBehavior {
  NSSplitViewItemCollapseBehaviorDefault,
  NSSplitViewItemCollapseBehaviorPreferResizingSplitViewWithFixedSiblings,
  NSSplitViewItemCollapseBehaviorPreferResizingSiblingsWithFixedSplitView,
  NSSplitViewItemCollapseBehaviorUseConstraints,
}

