declare enum NSURLSessionTaskMetricsResourceFetchType {
  NSURLSessionTaskMetricsResourceFetchTypeUnknown,
  NSURLSessionTaskMetricsResourceFetchTypeNetworkLoad,
  NSURLSessionTaskMetricsResourceFetchTypeServerPush,
  NSURLSessionTaskMetricsResourceFetchTypeLocalCache,
}

