declare enum NSURLBookmarkCreationOptions {
  NSURLBookmarkCreationPreferFileIDResolution,
  NSURLBookmarkCreationMinimalBookmark,
  NSURLBookmarkCreationSuitableForBookmarkFile,
  NSURLBookmarkCreationWithSecurityScope,
  NSURLBookmarkCreationSecurityScopeAllowOnlyReadAccess,
}

