root: true
parser: '@typescript-eslint/parser'
extends:
  - airbnb-base
  - prettier
plugins:
  - typescript
  - babel
  - prettier

globals:
  NSFont: false
  MOPointer: false
  NSMakeRange: false
  NSMaxRange: false
  MSSelfContainedHighLevelExporter: false
  MSLayerMovement: false
  NSMakeRect: false
  MSBitmapLayer: false
  MSLayerGroup: false
  MSTextLayer: false
  MSShapeGroup: false
  NSArray: false
  NSMakePoint: false
  CGRectMake: false
  MSArtboardGroup: false
  MSPage: false
  MSApplicationMetadata: false
  log: false
  NSApplication: false
  NSDocumentController: false
  NSAlert: false
  NSComboBox: false
  NSUserDefaults: false
  AppController: false
  MSImageData: false
  NSImage: false
  NSTextField: false
  NSSlider: false
  MSStyleFill: false
  MSStyleBorder: false
  MSColor: false
  MSImmutableColor: false
  MSDefaultStyle: false
  MSLayer: false
  MSDocumentData: false
  MSSymbolMaster: false
  MSSymbolInstance: false
  MSAvailableOverride: false
  MSAssetLibrary: false
  MSDocument: false
  NSURL: false
  NSSaveToOperation: false
  NSData: false
  NSDataBase64DecodingIgnoreUnknownCharacters: false
  __command: false
  MSFlowConnection: false
  MSHotspotLayer: false
  NSPredicate: false
  MSRectangleShape: false
  MSSymbolMasterReference: false
  MSShareableObjectReference: false
  MSSharedStyleReference: false
  NSString: false
  MSForeignSymbolProvider: false
  MSForeignObjectCollector: false
  MSStyleShadow: false
  MSStyleInnerShadow: false
  MSGradientStop: false
  MSImmutableGradientStop: false
  MSGradient: false
  MSImmutableGradient: false
  CGPointMake: false
  MSSharedLayerReference: false
  MSSharedTextReference: false
  MSUserAssetLibrary: false
  MSRemoteAssetLibrary: false
  NSSaveAsOperation: false
  NSSaveOperation: false
  coscript: false
  __mocha__: false
  NSOpenPanel: false
  NSOKButton: false
  NSNull: false
  MSSharedLayerStyleProvider: false
  MSSharedTextStyleProvider: false
  MSForeignObjectProvider: false
  MSSharedStyle: false
  MSStyle: false
  MSDataOverride: false
  MSImmutableArtboardGroup: false
  MSImmutableLayerGroup: false
  MSImmutableHotspotLayer: false
  MSImmutableBitmapLayer: false
  MSImmutableLayer: false
  MSImmutablePage: false
  MSImmutableShapeGroup: false
  MSStyledLayer: false
  MSImmutableStyledLayer: false
  MSImmutableSymbolInstance: false
  MSImmutableSymbolMaster: false
  MSImmutableTextLayer: false
  MSImmutableDocumentData: false
  MSShapePathLayer: false
  MSOvalShape: false
  MSPolygonShape: false
  MSStarShape: false
  MSTriangleShape: false
  MSImmutableShapePathLayer: false
  MSImmutableOvalShape: false
  MSImmutablePolygonShape: false
  MSImmutableStarShape: false
  MSImmutableTriangleShape: false
  MSImmutableRectangleShape: false
  NSParagraphStyleAttributeName: false
  NSParagraphStyle: false
  MSTextStyle: false
  NSKernAttributeName: false
  NSFontAttributeName: false
  NSFontManager: false
  NSBoldFontMask: false
  NSItalicFontMask: false
  NSSmallCapsFontMask: false
  NSCompressedFontMask: false
  NSCondensedFontMask: false
  NSExpandedFontMask: false
  NSNarrowFontMask: false
  NSPosterFontMask: false
  MSDefaultTextStyle: false
  NSUnderlineStyleAttributeName: false
  NSStrikethroughStyleAttributeName: false
  MSSliceLayer: false
  MSImmutableSliceLayer: false
  MSExportFormat: false
  NSThread: false
  MSTheme: false
  MSCurvePoint: false
  MSPath: false
  SVGPathInterpreter: false
  NSBezierPath: false
  MSJSONDataArchiver: false
  MSJSONDictionaryUnarchiver: false
  MSArchiveHeader: false
  NSUTF8StringEncoding: false
  MSExportRequest: false
  MSExportManager: false
  NSFileManager: false
  NSDataWritingWithoutOverwriting: false
  MSColorAsset: false
  MSGradientAsset: false
  MSPersistentAssetCollection: false
  MSOverrideProperty: false
  MSOverridePoint: false
  NSMutableArray: false
  CGRectNull: false
  NSColorSpace: false
  NSColor: false
  MSExporter: false
  MSSVGImporter: false
  MSPDFImporter: false
  NSApp: false
  CGPathGetBoundingBox: false
  MSShapeEventHandler: false
  NSIndexPath: false
  NSScrollView: false
  NSViewWidthSizable: false
  NSViewHeightSizable: false
  NSTextView: false
  NSMakeSize: false
  NSPopUpButton: false

rules:
  ###########
  # PLUGINS #
  ###########
  # IMPORT
  import/prefer-default-export: off
  import/no-extraneous-dependencies: off
  import/extensions: off
  import/no-unresolved:
    - error
    - commonjs: true
      caseSensitive: true
      ignore:
        - '^sketch(\/|$)'
  # TYPESCRIPT
  typescript/interface-name-prefix:
    - error
    - always
  typescript/no-angle-bracket-type-assertion: error
  # typescript/explicit-member-accessibility: error
  typescript/no-unused-vars: error
  typescript/no-use-before-define:
    - error
    - functions: false
      variables: false
      typedefs: false
  ## blocked by https://github.com/nzakas/eslint-plugin-typescript/pull/23
  # typescript/member-ordering: error
  ##
  ## blocked by https://github.com/nzakas/eslint-plugin-typescript/issues/41
  # typescript/type-annotation-spacing: error
  ##

  # Babel
  babel/no-invalid-this: error

  ###########
  # BUILTIN #
  ###########
  no-underscore-dangle: off
  class-methods-use-this: warn
  no-useless-constructor: warn
  eqeqeq: off
  strict: off

  ###########
  # SPECIAL #
  ###########
  prettier/prettier:
    - error
    - singleQuote: true
      trailingComma: es5
      semi: false
      parser: typescript
  no-restricted-syntax:
    - error
    # no-default-export
    - selector: ExportDefaultDeclaration
      message: Use of default exports is forbidden

parserOptions:
  sourceType: module

settings:
  import/resolver:
    node:
      extensions:
        - .ts
        - .js
        - .json
