root: true
parser: typescript-eslint-parser
extends:
  - airbnb-base
  - prettier
plugins:
  - typescript
  - babel
  - prettier

globals:
  NSFont: false
  MOPointer: false
  NSMakeRange: false
  NSMaxRange: false
  MSSelfContainedHighLevelExporter: false
  MSLayerMovement: false
  NSMakeRect: false
  MSBitmapLayer: false
  MSLayerGroup: false
  MSTextLayer: false
  MSShapeGroup: false
  NSArray: false
  NSTask: false
  NSMakePoint: false
  CGRectMake: false
  MSArtboardGroup: false
  MSPage: false
  MSApplicationMetadata: false
  log: false
  NSApplication: false
  NSDocumentController: false
  NSAlert: false
  NSComboBox: false
  NSUserDefaults: false
  AppController: false
  MSImageData: false
  NSImage: false
  MSModalInputSheet: false
  MSStyleFill: false
  MSStyleBorder: false
  MSColor: false
  MSImmutableColor: false
  MSDefaultStyle: false
  MSLayer: false
  MSDocumentData: false
  MSSymbolMaster: false
  MSSymbolInstance: false
  MSAvailableOverride: false
  NSData: false
  NSDataBase64DecodingIgnoreUnknownCharacters: false
  MSDocument: false
  __command: false
  MSFlowConnection: false
  MSHotspotLayer: false
  NSPredicate: false
  MSRectangleShape: false
  MSStyleShadow: false
  MSStyleInnerShadow: false
  MSGradientStop: false
  MSGradient: false
  CGPointMake: false

rules:
  ###########
  # PLUGINS #
  ###########
  # IMPORT
  import/prefer-default-export: off
  import/no-extraneous-dependencies: off
  # TYPESCRIPT
  typescript/interface-name-prefix:
    - error
    - always
  typescript/no-angle-bracket-type-assertion: error
  # typescript/explicit-member-accessibility: error
  typescript/no-unused-vars: error
  typescript/no-use-before-define:
    - error
    - functions: false
      variables: false
      typedefs: false
  ## blocked by https://github.com/nzakas/eslint-plugin-typescript/pull/23
  # typescript/member-ordering: error
  ##
  ## blocked by https://github.com/nzakas/eslint-plugin-typescript/issues/41
  # typescript/type-annotation-spacing: error
  ##

  # Babel
  babel/no-invalid-this: error

  ###########
  # BUILTIN #
  ###########
  no-underscore-dangle: off
  class-methods-use-this: warn
  no-useless-constructor: warn
  eqeqeq: off
  strict: off

  ###########
  # SPECIAL #
  ###########
  prettier/prettier:
    - error
    - singleQuote: true
      trailingComma: es5
      semi: false
      parser: typescript
  no-restricted-syntax:
    - error
    # no-default-export
    - selector: ExportDefaultDeclaration
      message: Use of default exports is forbidden

parserOptions:
  sourceType: module
