# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.8

    working_directory: ~/repo

    steps:
      - checkout

      # Download the cached dependencies that correspond to the package.json
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}

      # if we haven't found a cache, we need to run a npm install
      # We also run it when we find one, just in case
      - run: npm install
      - run: sudo apt-get -y -qq install awscli

      # cache the dependencies for next time
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Lint
      - run: npm run lint

      # build and store the artifacts so that we can access them
      - run: npm run build
      - run: aws s3 sync ~/repo/build/ s3://sketch-api/$CIRCLE_PR_NUMBER --region eu-west-1

      # check if the PR is "correct". See dangerfile.ts for more information
      - run: ./node_modules/.bin/danger ci
