#!/usr/bin/env python

import os

actions = [
    "InsertMenu",
    "InsertVector",
    "Pencil",
    "InsertTextLayer",
    "InsertImage",
    "InsertSlice",
    "InsertArtboard",
    "InsertLine",
    "InsertArrow",
    "Shape",
    "RectangleShape",
    "RoundedRectangleShape",
    "OvalShape",
    "TriangleShape",
    "PolygonShape",
    "StarShape",
    "InsertSymbol",
    "InsertSharedText",
    "Group",
    "Ungroup",
    "BooleanMenu",
    "Union",
    "Subtract",
    "Intersect",
    "Difference",
    "MoveForward",
    "MoveBackward",
    "MoveToFront",
    "MoveToBack",
    "DistributeHorizontally",
    "DistributeVertically",
    "ToolsMenu",
    "Transform",
    "Flatten",
    "Scissors",
    "SmartRotate",
    "Edit",
    "Rotate",
    "ConvertToOutlines",
    "Scale",
    "MaskWithShape",
    "ViewMenu",
    "ToggleRulers",
    "ToggleGrid",
    "ToggleLayout",
    "TogglePixelGrid",
    "Export",
    "HideLayer",
    "LockLayer",
    "TogglePresentationMode",
    "SpiralShape",
    "FlattenSelection",
    "RoundToPixel",
    "NineSlice",
    "ResetBoolean",
    "CreateSymbol",
    "CreateSharedStyle",
    "SyncSharedStyle",
    "ResetSharedStyle",
    "Print",
    "Zoom",
    "MakeGrid",
    "MakeLowercase",
    "MakeUppercase",
    "Underline",
    "AlignLeft",
    "AlignCenter",
    "AlignRight",
    "AlignJustified",
    "SaveAsTemplate",
    "FlipHorizontal",
    "FlipVertical",
    "ClippingMask",
    "ClippingMaskMode",
    "IgnoreClippingMask",
    "ToggleFill",
    "TextOnPath",
    "ToggleBorder",
    "Join",
    "Split",
    "ReduceImageSize",
    "ReplaceImage",
    "ImageOriginalSize",
    "ClosePath",
    "BaseAlignLayers",
    "AlignLayersLeft",
    "AlignLayersCenter",
    "AlignLayersRight",
    "AlignLayersTop",
    "AlignLayersMiddle",
    "AlignLayersBottom",
    "AutoExpandGroups",
    "CollapseAllGroups",
    "RevealInLayerList",
    "HideAllGridsAndLayouts",
    "BaseStyle",
    "AddFill",
    "AddBorder",
    "AddShadow",
    "AddInnerShadow",
    "ShowFillOptions",
    "ShowBorderOptions",
    "RemoveUnusedStyles",
    "Mirror",
    "Publish",
    "ResizeArtboardToFit",
    "BackToInstance",
    "DetachSybolInstances",
    "SelectAllArtboards",
    "AddExportFormat",
    "ToggleArtboardShadow",
    "ToggleAlignmentGuides",
    "TogglePixelLines",
    "ToggleSelection",
    "ToggleLayerHighlight",
]

fakeActions = [
    "DocumentSaved",
    "OpenDocument",
    "CloseDocument",
    "ExportSlices",
    "SelectionChanged",
    "ArtboardChanged",
    "LayersMoved",
    "TextChanged"
]

allActions = actions + fakeActions

actionsPath = "_actions"
if not os.path.exists(actionsPath):
    os.mkdir(actionsPath)

for action in allActions:
    with open(os.path.join(actionsPath, action +".md"), "w") as f:
        stub = "---\ntitle: {0}\nsummary: work in progress\n---\n\nWork In Progress\n\nDocumentation for the {0} action will appear here.".format(action)
        f.write(stub)
